# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MAGNOSH
email: maagnoreiz@gmail.com
description: Este site tem o próposito de compartilhar meu conhecimento com o público, todos meus pensamentos e assuntos
do meu interesse, escrito por mim, Magno Reis
baseurl: /magnosh
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: halcance
github_username:  halcance

# Build settings
markdown: kramdown
excerpt_separator: <!--- more -->
